[package]
name = "rust_secret"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#actix-web = "4"
#actix-files = "0.6.2"
axum = { version = "*"}
tokio = { version = "1", features = ["full"] }
rusqlite = "0.29.0"
hyper = "0.14.27"
#diesel ="2.1.3"
dotenv = "0.15.0"
tera = "1"
chrono = "0.4.31"