[package]
name = "rust_secret"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-files = "0.6.2"
diesel ="2.1.3"
dotenv = "0.15.0"
tera = "1"
lazy_static = "1.4.0"